$(document).ready(function(){
	$.getJSON("https://spreadsheets.google.com/feeds/list/1V1Lvg5AIKx9k0YmRhmTxYtv1Pn9dbTI--D8ejGKwPtk/od6/public/values?alt=json", 
	function(data){ 
		data = data['feed']['entry'];
		console.log(data);
		showGoods(data);
	});
	
	function showGoods(data){
		var out ='';
		
		for(var i=0; i<data.length; i++){
			out += `<Div class="boxi">`;
			out += `<Div class="boxChar">`;
			out += `<Div class="boxNik">`;
			out += `${data[i]['gsx$nik']['$t']}`;
			out += `<br>`;
			out += `<Div class="boxLvL">`;
			out += `${data[i]['gsx$ур']['$t']}`;
			out += `+`;
			out += `${data[i]['gsx$хм']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxInv">`;
			out += `<Div class="InvName"><b>Бижутерия</b><Br></Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Кольцо</b><Br></Div>`;
			out += `${data[i]['gsx$кольцо']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$уркольца']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Cерьга</b><Br></Div>`;
			out += `${data[i]['gsx$серьга']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урсерьги']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Ожерелья</b><Br></Div>`;
			out += `${data[i]['gsx$ожерелья']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урожерелья']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Браслет</b><Br></Div>`;
			out += `${data[i]['gsx$браслет']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урбраслета']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Пояс</b><Br></Div>`;
			out += `${data[i]['gsx$пояс']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урпояса']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Перчатка</b><Br></Div>`;
			out += `${data[i]['gsx$перчатка']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урперчатки']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxInv">`;
			out += `<Div class="InvName"><b>Шарики</b><Br></Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Сфера</b><Br></Div>`;
			out += `${data[i]['gsx$сфера']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урсферы']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Душа</b><Br></Div>`;
			out += `${data[i]['gsx$душа']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урдуши']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Петомиц</b><Br></Div>`;
			out += `${data[i]['gsx$петомиц']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урпетомца']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxInv">`;
			out += `<Div class="InvName"><b>Доп предметы</b><Br></Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Символ</b><Br></Div>`;
			out += `${data[i]['gsx$символ']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Подвеска</b><Br></Div>`;
			out += `${data[i]['gsx$подвеска']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxInv">`;
			out += `<Div class="InvName"><b>Триграммы</b><Br></Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 1</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма1']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 2</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма2']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 3</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма3']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 4</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма4']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 5</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма5']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 6</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма6']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 7</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма7']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Триграмма 8</b><Br></Div>`;
			out += `${data[i]['gsx$триграмма8']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxInv">`;
			out += `<Div class="InvName"><b>Оружие</b><Br></Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `${data[i]['gsx$оружие']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$уроружия']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxInv">`;
			out += `<Div class="InvName"><b>Професии</b><Br></Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Професия1</b><Br></Div>`;
			out += `${data[i]['gsx$професия1']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урпрофесии1']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Професия2</b><Br></Div>`;
			out += `${data[i]['gsx$професия2']['$t']}`;
			out += `</Div>`;
			out += `<Div class="boxItemLvL">`;
			out += `${data[i]['gsx$урпрофесии2']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxInv">`;
			out += `<Div class="InvName"><b>Деньги</b><Br></Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Золото</b><Br></Div>`;
			out += `${data[i]['gsx$золото']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Серебро</b><Br></Div>`;
			out += `${data[i]['gsx$серебро']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `<Div class="boxGear">`;
			out += `<Div class="boxItem">`;
			out += `<Div class="ItemName"><b>Медь</b><Br></Div>`;
			out += `${data[i]['gsx$медь']['$t']}`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
			out += `</Div>`;
		}
		$('.sendboxx').html(out);
		
	}
})